name: Publish Doc

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - docs/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Jekyll
        run: |
          gem install --install-dir $HOME/vendor/bundle jekyll
          echo "GEM_HOME=$HOME/vendor/bundle" >> $GITHUB_ENV
          echo "GEM_PATH=$HOME/vendor/bundle" >> $GITHUB_ENV
          echo "$HOME/vendor/bundle/bin" >> $GITHUB_PATH
      - name: Build docs
        run: |
          sbt docs/makeMicrosite
      - name: publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/target/site
          publish_branch: gh-pages
